{{- $envSecret := lookup "v1" "Secret" .Release.Namespace "worldmonitor-env" }}
apiVersion: v1
kind: Secret
metadata:
  name: worldmonitor-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  UPSTASH_REDIS_REST_TOKEN: {{ if $envSecret }}{{ index $envSecret.data "UPSTASH_REDIS_REST_TOKEN" | b64dec | quote }}{{ else }}{{ randAlphaNum 32 | quote }}{{ end }}
  LLM_API_URL: {{ .Values.env.llmApiUrl | quote }}
  LLM_API_KEY: {{ .Values.env.llmApiKey | quote }}
  LLM_MODEL: {{ .Values.env.llmModel | quote }}
  GROQ_API_KEY: {{ .Values.env.groqApiKey | quote }}
  OPENROUTER_API_KEY: {{ .Values.env.openrouterApiKey | quote }}
  AISSTREAM_API_KEY: {{ .Values.env.aistreamApiKey | quote }}
  FINNHUB_API_KEY: {{ .Values.env.finnhubApiKey | quote }}
  EIA_API_KEY: {{ .Values.env.eiaApiKey | quote }}
  FRED_API_KEY: {{ .Values.env.fredApiKey | quote }}
  ACLED_ACCESS_TOKEN: {{ .Values.env.acledAccessToken | quote }}
  NASA_FIRMS_API_KEY: {{ .Values.env.nasaFirmsApiKey | quote }}
  CLOUDFLARE_API_TOKEN: {{ .Values.env.cloudflareApiToken | quote }}
  AVIATIONSTACK_API: {{ .Values.env.aviationstackApi | quote }}